### ISSUE TITLE
Show more details on EVM nft transfer

### ISSUE THREAD

**Issue by tanglepay-dev** [TanglePay/TanglePay#127]

**Comment by zkk333** [comment]
@daihanqiao 报了out of  gas  而且试了更小的gas fee
 也是报这个。。

![Image](https://github.com/TanglePay/TanglePay/assets/42662926/e6f17c55-c182-4ecf-b79b-a86aae8a7605)

**Comment by zkk333** [comment]
现在的主要问题是nft转走后pool的归属不对以及接收方无法自动接收转过来的nft

**Comment by zkk333** [comment]
测试通过，当划转完lp token的nft后，pool也会转到对应的地址下，这时候无论是移除还是添加流动性还是farm都是可以的

**Comment by zkk333** [comment]
![Image](https://github.com/TanglePay/TanglePay/assets/42662926/fe87661f-b91d-4a29-990e-6272f0fec9a7)
