### ISSUE TITLE
Incorrect asset display after value transfer

### ISSUE THREAD

**Issue by tanglepay-dev** [TanglePay/TanglePay#136]
smr完成向外转账后，回到首页，可用smr数量会偏小。重新刷新（加载）后数据正常。
应该是发生转出的output里面的值在算smr数量时，没有及时被加进来。

**Comment by zkk333** [comment]
暂时插件端测试没问题，一共加起来大概测试了200次左右  ios端等出新包再测

**Comment by zkk333** [comment]
测试通过
