### ISSUE TITLE
Been 2 months, again no help from developers

### ISSUE THREAD

**Issue by wireless90** [TanglePay/TanglePay#149]
Web extension, Shimmer Testnet: Asset Sync failed
Mobile wallet, Shimmer Testnet: Asset Sync failed

Been asking multiple times in discord. No help at all. 

Have told in telegram. No help at all.

**Comment by tanglepay-dev** [comment]
sorry @wireless90, will be looking into this.

**Comment by wireless90** [comment]
Thank you guys, sorry as my demo project to bosses involves TanglePay and TanglePaySDK and the previous presentation i could not show it fully as asset sync failed. Coming 31st Jan i have another demo to bosses, hopefully will be fixed by then.

**Comment by tanglepay-dev** [comment]
> Thank you guys, sorry as my demo project to bosses involves TanglePay and TanglePaySDK and the previous presentation i could not show it fully as asset sync failed. Coming 31st Jan i have another demo to bosses, hopefully will be fixed by then.

Hope you had a good demo. I think it was fixed ~10 days ago. Please let us know if encountered with more issues.

**Comment by wireless90** [comment]
opening this again, we are again encountering asset sync issues in testnet on both android wallet and chrome extension. Furthermore, testnet wallets's mnemonic cant be used to import wallet. Perhaps  its because of the asset sync failed issue.
